In [1]:
import numpy as np

In [2]:
np.array([[0.5774, 0.5774, 0.5774, 0.5774], [0.5774, 0.5774, 0.5774, 0.5774]])


array([[0.5774, 0.5774, 0.5774, 0.5774],
       [0.5774, 0.5774, 0.5774, 0.5774]])

In [3]:
np.array([[0.5774, 0.5774, 0.5774, 0.5774]])

array([[0.5774, 0.5774, 0.5774, 0.5774]])

In [7]:
np.repeat([[0.5774, 0.5774, 0.5774, 0.5774]], repeats=3, axis=0)

array([[0.5774, 0.5774, 0.5774, 0.5774],
       [0.5774, 0.5774, 0.5774, 0.5774],
       [0.5774, 0.5774, 0.5774, 0.5774]])